/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

@SuppressWarnings("java:S106")
public class Main {
    public static void main(String... args) {
        System.out.println("Hello World!");
    }
}
